// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pb/bank_request.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BankRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransactionId  string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PayerAccountId string                 `protobuf:"bytes,2,opt,name=payer_account_id,json=payerAccountId,proto3" json:"payer_account_id,omitempty"`
	PayeeAccountId string                 `protobuf:"bytes,3,opt,name=payee_account_id,json=payeeAccountId,proto3" json:"payee_account_id,omitempty"`
	Amount         int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	BankCode       string                 `protobuf:"bytes,5,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*BankRequest_Debit
	//	*BankRequest_Credit
	Operation     isBankRequest_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankRequest) Reset() {
	*x = BankRequest{}
	mi := &file_pb_bank_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankRequest) ProtoMessage() {}

func (x *BankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bank_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankRequest.ProtoReflect.Descriptor instead.
func (*BankRequest) Descriptor() ([]byte, []int) {
	return file_pb_bank_request_proto_rawDescGZIP(), []int{0}
}

func (x *BankRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BankRequest) GetPayerAccountId() string {
	if x != nil {
		return x.PayerAccountId
	}
	return ""
}

func (x *BankRequest) GetPayeeAccountId() string {
	if x != nil {
		return x.PayeeAccountId
	}
	return ""
}

func (x *BankRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BankRequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *BankRequest) GetOperation() isBankRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *BankRequest) GetDebit() *DebitDetails {
	if x != nil {
		if x, ok := x.Operation.(*BankRequest_Debit); ok {
			return x.Debit
		}
	}
	return nil
}

func (x *BankRequest) GetCredit() *CreditDetails {
	if x != nil {
		if x, ok := x.Operation.(*BankRequest_Credit); ok {
			return x.Credit
		}
	}
	return nil
}

type isBankRequest_Operation interface {
	isBankRequest_Operation()
}

type BankRequest_Debit struct {
	Debit *DebitDetails `protobuf:"bytes,6,opt,name=debit,proto3,oneof"`
}

type BankRequest_Credit struct {
	Credit *CreditDetails `protobuf:"bytes,7,opt,name=credit,proto3,oneof"`
}

func (*BankRequest_Debit) isBankRequest_Operation() {}

func (*BankRequest_Credit) isBankRequest_Operation() {}

type DebitDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mpin          string                 `protobuf:"bytes,1,opt,name=mpin,proto3" json:"mpin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitDetails) Reset() {
	*x = DebitDetails{}
	mi := &file_pb_bank_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitDetails) ProtoMessage() {}

func (x *DebitDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bank_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitDetails.ProtoReflect.Descriptor instead.
func (*DebitDetails) Descriptor() ([]byte, []int) {
	return file_pb_bank_request_proto_rawDescGZIP(), []int{1}
}

func (x *DebitDetails) GetMpin() string {
	if x != nil {
		return x.Mpin
	}
	return ""
}

type CreditDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditDetails) Reset() {
	*x = CreditDetails{}
	mi := &file_pb_bank_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditDetails) ProtoMessage() {}

func (x *CreditDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bank_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditDetails.ProtoReflect.Descriptor instead.
func (*CreditDetails) Descriptor() ([]byte, []int) {
	return file_pb_bank_request_proto_rawDescGZIP(), []int{2}
}

var File_pb_bank_request_proto protoreflect.FileDescriptor

const file_pb_bank_request_proto_rawDesc = "" +
	"\n" +
	"\x15pb/bank_request.proto\x12\x02pb\"\xa1\x02\n" +
	"\vBankRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12(\n" +
	"\x10payer_account_id\x18\x02 \x01(\tR\x0epayerAccountId\x12(\n" +
	"\x10payee_account_id\x18\x03 \x01(\tR\x0epayeeAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1b\n" +
	"\tbank_code\x18\x05 \x01(\tR\bbankCode\x12(\n" +
	"\x05debit\x18\x06 \x01(\v2\x10.pb.DebitDetailsH\x00R\x05debit\x12+\n" +
	"\x06credit\x18\a \x01(\v2\x11.pb.CreditDetailsH\x00R\x06creditB\v\n" +
	"\toperation\"\"\n" +
	"\fDebitDetails\x12\x12\n" +
	"\x04mpin\x18\x01 \x01(\tR\x04mpin\"\x0f\n" +
	"\rCreditDetailsB'Z%github.com/swastiijain24/contracts/pbb\x06proto3"

var (
	file_pb_bank_request_proto_rawDescOnce sync.Once
	file_pb_bank_request_proto_rawDescData []byte
)

func file_pb_bank_request_proto_rawDescGZIP() []byte {
	file_pb_bank_request_proto_rawDescOnce.Do(func() {
		file_pb_bank_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_bank_request_proto_rawDesc), len(file_pb_bank_request_proto_rawDesc)))
	})
	return file_pb_bank_request_proto_rawDescData
}

var file_pb_bank_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_bank_request_proto_goTypes = []any{
	(*BankRequest)(nil),   // 0: pb.BankRequest
	(*DebitDetails)(nil),  // 1: pb.DebitDetails
	(*CreditDetails)(nil), // 2: pb.CreditDetails
}
var file_pb_bank_request_proto_depIdxs = []int32{
	1, // 0: pb.BankRequest.debit:type_name -> pb.DebitDetails
	2, // 1: pb.BankRequest.credit:type_name -> pb.CreditDetails
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_bank_request_proto_init() }
func file_pb_bank_request_proto_init() {
	if File_pb_bank_request_proto != nil {
		return
	}
	file_pb_bank_request_proto_msgTypes[0].OneofWrappers = []any{
		(*BankRequest_Debit)(nil),
		(*BankRequest_Credit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_bank_request_proto_rawDesc), len(file_pb_bank_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_bank_request_proto_goTypes,
		DependencyIndexes: file_pb_bank_request_proto_depIdxs,
		MessageInfos:      file_pb_bank_request_proto_msgTypes,
	}.Build()
	File_pb_bank_request_proto = out.File
	file_pb_bank_request_proto_goTypes = nil
	file_pb_bank_request_proto_depIdxs = nil
}
