// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pb/bank_response.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BankResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	BankReferenceId string                 `protobuf:"bytes,2,opt,name=bank_reference_id,json=bankReferenceId,proto3" json:"bank_reference_id,omitempty"`
	Success         bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Type            string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BankResponse) Reset() {
	*x = BankResponse{}
	mi := &file_pb_bank_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankResponse) ProtoMessage() {}

func (x *BankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bank_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankResponse.ProtoReflect.Descriptor instead.
func (*BankResponse) Descriptor() ([]byte, []int) {
	return file_pb_bank_response_proto_rawDescGZIP(), []int{0}
}

func (x *BankResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BankResponse) GetBankReferenceId() string {
	if x != nil {
		return x.BankReferenceId
	}
	return ""
}

func (x *BankResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BankResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BankResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_pb_bank_response_proto protoreflect.FileDescriptor

const file_pb_bank_response_proto_rawDesc = "" +
	"\n" +
	"\x16pb/bank_response.proto\x12\x02pb\"\xb4\x01\n" +
	"\fBankResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12*\n" +
	"\x11bank_reference_id\x18\x02 \x01(\tR\x0fbankReferenceId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04typeB'Z%github.com/swastiijain24/contracts/pbb\x06proto3"

var (
	file_pb_bank_response_proto_rawDescOnce sync.Once
	file_pb_bank_response_proto_rawDescData []byte
)

func file_pb_bank_response_proto_rawDescGZIP() []byte {
	file_pb_bank_response_proto_rawDescOnce.Do(func() {
		file_pb_bank_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_bank_response_proto_rawDesc), len(file_pb_bank_response_proto_rawDesc)))
	})
	return file_pb_bank_response_proto_rawDescData
}

var file_pb_bank_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_bank_response_proto_goTypes = []any{
	(*BankResponse)(nil), // 0: pb.BankResponse
}
var file_pb_bank_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_bank_response_proto_init() }
func file_pb_bank_response_proto_init() {
	if File_pb_bank_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_bank_response_proto_rawDesc), len(file_pb_bank_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_bank_response_proto_goTypes,
		DependencyIndexes: file_pb_bank_response_proto_depIdxs,
		MessageInfos:      file_pb_bank_response_proto_msgTypes,
	}.Build()
	File_pb_bank_response_proto = out.File
	file_pb_bank_response_proto_goTypes = nil
	file_pb_bank_response_proto_depIdxs = nil
}
