// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pb/payment_response.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	DebitBankRef  string                 `protobuf:"bytes,3,opt,name=debit_bank_ref,json=debitBankRef,proto3" json:"debit_bank_ref,omitempty"`
	CreditBankRef string                 `protobuf:"bytes,4,opt,name=credit_bank_ref,json=creditBankRef,proto3" json:"credit_bank_ref,omitempty"`
	FailureReason string                 `protobuf:"bytes,5,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_pb_payment_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_payment_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_pb_payment_response_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentResponse) GetDebitBankRef() string {
	if x != nil {
		return x.DebitBankRef
	}
	return ""
}

func (x *PaymentResponse) GetCreditBankRef() string {
	if x != nil {
		return x.CreditBankRef
	}
	return ""
}

func (x *PaymentResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *PaymentResponse) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

var File_pb_payment_response_proto protoreflect.FileDescriptor

const file_pb_payment_response_proto_rawDesc = "" +
	"\n" +
	"\x19pb/payment_response.proto\x12\x02pb\"\xe8\x01\n" +
	"\x0fPaymentResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12$\n" +
	"\x0edebit_bank_ref\x18\x03 \x01(\tR\fdebitBankRef\x12&\n" +
	"\x0fcredit_bank_ref\x18\x04 \x01(\tR\rcreditBankRef\x12%\n" +
	"\x0efailure_reason\x18\x05 \x01(\tR\rfailureReason\x12!\n" +
	"\fcompleted_at\x18\x06 \x01(\tR\vcompletedAtB'Z%github.com/swastiijain24/contracts/pbb\x06proto3"

var (
	file_pb_payment_response_proto_rawDescOnce sync.Once
	file_pb_payment_response_proto_rawDescData []byte
)

func file_pb_payment_response_proto_rawDescGZIP() []byte {
	file_pb_payment_response_proto_rawDescOnce.Do(func() {
		file_pb_payment_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_payment_response_proto_rawDesc), len(file_pb_payment_response_proto_rawDesc)))
	})
	return file_pb_payment_response_proto_rawDescData
}

var file_pb_payment_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_payment_response_proto_goTypes = []any{
	(*PaymentResponse)(nil), // 0: pb.PaymentResponse
}
var file_pb_payment_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_payment_response_proto_init() }
func file_pb_payment_response_proto_init() {
	if File_pb_payment_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_payment_response_proto_rawDesc), len(file_pb_payment_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_payment_response_proto_goTypes,
		DependencyIndexes: file_pb_payment_response_proto_depIdxs,
		MessageInfos:      file_pb_payment_response_proto_msgTypes,
	}.Build()
	File_pb_payment_response_proto = out.File
	file_pb_payment_response_proto_goTypes = nil
	file_pb_payment_response_proto_depIdxs = nil
}
