// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type VpaMap struct {
	ID        pgtype.UUID        `json:"id"`
	VpaID     string             `json:"vpa_id"`
	AccountID string             `json:"account_id"`
	BankCode  string             `json:"bank_code"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
