// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: psp_queries.sql

package repo

import (
	"context"
)

const getPspRegistration = `-- name: GetPspRegistration :one
SELECT psp_id, hashed_api_key, psp_name, is_active, created_at
FROM psp_registrations 
WHERE psp_id = $1
`

func (q *Queries) GetPspRegistration(ctx context.Context, pspID string) (PspRegistration, error) {
	row := q.db.QueryRow(ctx, getPspRegistration, pspID)
	var i PspRegistration
	err := row.Scan(
		&i.PspID,
		&i.HashedApiKey,
		&i.PspName,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const isActive = `-- name: IsActive :one
SELECT EXISTS (
    SELECT 1 FROM psp_registrations
    WHERE psp_id = $1
      AND is_active = TRUE
)
`

func (q *Queries) IsActive(ctx context.Context, pspID string) (bool, error) {
	row := q.db.QueryRow(ctx, isActive, pspID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
