// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CheckVpaExists(ctx context.Context, vpaID string) (bool, error)
	CreateVpaMapping(ctx context.Context, arg CreateVpaMappingParams) (VpaMap, error)
	DeactivateVpa(ctx context.Context, vpaID string) error
	GetVpaMapping(ctx context.Context, vpaID string) (GetVpaMappingRow, error)
}

var _ Querier = (*Queries)(nil)
