// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vpa_queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVpaMapping = `-- name: CreateVpaMapping :one
INSERT INTO vpa_map (
    vpa_id, account_id, bank_code
) VALUES (
    $1, $2, $3
)
RETURNING id, vpa_id, account_id, bank_code, is_active, created_at, updated_at
`

type CreateVpaMappingParams struct {
	VpaID     string `json:"vpa_id"`
	AccountID string `json:"account_id"`
	BankCode  string `json:"bank_code"`
}

func (q *Queries) CreateVpaMapping(ctx context.Context, arg CreateVpaMappingParams) (VpaMap, error) {
	row := q.db.QueryRow(ctx, createVpaMapping, arg.VpaID, arg.AccountID, arg.BankCode)
	var i VpaMap
	err := row.Scan(
		&i.ID,
		&i.VpaID,
		&i.AccountID,
		&i.BankCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateVpa = `-- name: DeactivateVpa :exec
UPDATE vpa_map
SET is_active = false, updated_at = CURRENT_TIMESTAMP
WHERE vpa_id = $1
`

func (q *Queries) DeactivateVpa(ctx context.Context, vpaID string) error {
	_, err := q.db.Exec(ctx, deactivateVpa, vpaID)
	return err
}

const getVpaMapping = `-- name: GetVpaMapping :one
SELECT vpa_id, account_id, bank_code, is_active
FROM vpa_map
WHERE vpa_id = $1 LIMIT 1
`

type GetVpaMappingRow struct {
	VpaID     string      `json:"vpa_id"`
	AccountID string      `json:"account_id"`
	BankCode  string      `json:"bank_code"`
	IsActive  pgtype.Bool `json:"is_active"`
}

func (q *Queries) GetVpaMapping(ctx context.Context, vpaID string) (GetVpaMappingRow, error) {
	row := q.db.QueryRow(ctx, getVpaMapping, vpaID)
	var i GetVpaMappingRow
	err := row.Scan(
		&i.VpaID,
		&i.AccountID,
		&i.BankCode,
		&i.IsActive,
	)
	return i, err
}
